spring.application.name=gestao-produtos

# Conexao com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_produtos
spring.datasource.username=postgres
spring.datasource.password=Joao2026

# Configuraçoes do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true